export const dummy = [
    {
        id: "1",
        subject: "Team Meeting Recap",
        sender: "John Doe",
        date: new Date("2024-02-15T10:30:00"),
        body: "Hi team,\n\nHere's a quick recap of our last meeting. We discussed the project timeline and made some important decisions...\n\nBest regards,\nJohn",
        read: false,
        attachments: [
            { name: "meeting_notes.pdf" },
            { name: "project_timeline.xlsx" },
        ],
    },
    {
        id: "2",
        subject: "Quarterly Report",
        sender: "Finance Department",
        date: new Date("2024-02-10T14:45:00"),
        body: "Dear Colleagues,\n\nPlease find attached the quarterly financial report. Key highlights include...\n\nRegards,\nFinance Team",
        read: true,
        attachments: [{ name: "Q1_financial_report.pdf" }],
    },
    {
        id: "3",
        subject: "Vacation Request Approved",
        sender: "HR Department",
        date: new Date("2024-02-05T09:15:00"),
        body: "Dear Employee,\n\nYour vacation request for the upcoming month has been approved. Please coordinate with your team for any pending tasks.\n\nBest wishes,\nHR Team",
        read: false,
    },
    {
        id: "4",
        subject: "Product Update Webinar",
        sender: "Marketing Team",
        date: new Date("2024-01-28T11:20:00"),
        body: "Join us for an exciting webinar about our latest product updates. We'll be covering new features and improvements...\n\nRegards,\nMarketing",
        read: true,
    },
    {
        id: "5",
        subject: "Invitation to Company Hackathon",
        sender: "Innovation Team",
        date: new Date("2024-01-20T16:00:00"),
        body: "Calling all creative minds! We're organizing our annual company hackathon. Get ready to showcase your innovative ideas...\n\nCheers,\nInnovation Team",
        read: false,
    },
    {
        id: "6",
        subject: "Sales Performance Report Q4 2023",
        sender: "Sales Team",
        date: new Date("2024-01-15T15:30:00"),
        body: "Dear Team,\n\nHere's the sales performance report for Q4 2023. Key performance indicators are included...\n\nBest Regards,\nSales Team",
        read: true,
        attachments: [{ name: "Sales_Report_Q4_2023.xlsx" }],
    },
    {
        id: "7",
        subject: "New Project Proposal",
        sender: "Project Management Team",
        date: new Date("2024-02-08T10:00:00"),
        body: "This email outlines a new project proposal for the next quarter. Key features and requirements are detailed below...\n\nSincerely,\nProject Management",
        read: false,
    },
    {
        id: "8",
        subject: "Employee Feedback Survey",
        sender: "HR Department",
        date: new Date("2024-02-18T09:45:00"),
        body: "Dear Employees,\n\nKindly complete the employee feedback survey. Your feedback is important for our growth...\n\nThanks,\nHR Department",
        read: false,
    },
    {
        id: "9",
        subject: "IT System Maintenance",
        sender: "IT Department",
        date: new Date("2024-02-20T14:00:00"),
        body: "Dear Users,\n\nImportant notice regarding the upcoming IT system maintenance.  Please refer to the attached document for further details.\n\nSincerely,\nIT Department",
        read: false,
        attachments: [{ name: "IT_Maintenance_Schedule.pdf" }],
    },
    {
        id: "10",
        subject: "New Marketing Campaign Launch",
        sender: "Marketing Team",
        date: new Date("2024-03-01T11:25:00"),
        body: "We're excited to announce the launch of our new marketing campaign!  See the details in the attached document. \n\nBest,\nMarketing Team",
        read: false,
        attachments: [{ name: "New_Campaign_Details.docx" }],
    },
    {
        id: "11",
        subject: "Budget Allocation Q2 2024",
        sender: "Finance Team",
        date: new Date("2024-03-05T10:15:00"),
        body: "Good morning, \nThis email outlines the Q2 2024 budget allocation for all departments. Please review the attached document.\n\nSincerely,\nFinance Team",
        read: false,
        attachments: [{ name: "Budget_Allocation_Q2_2024.xlsx" }],
    },
    {
        id: "12",
        subject: "Training Schedule Update",
        sender: "Training Department",
        date: new Date("2024-03-08T11:40:00"),
        body: "Dear Employees, \nOur training schedule has been updated. Please check the attachment for revised timings and topics.\n\nBest,\nTraining Department",
        read: false,
        attachments: [{ name: "Training_Schedule_Update.pdf" }],
    },
    {
        id: "13",
        subject: "Recruitment Drive Announcement",
        sender: "HR Department",
        date: new Date("2024-03-12T14:30:00"),
        body: "Dear Applicants, \nWe're excited to announce our new recruitment drive for various positions. Please find the details attached. \n\nSincerely,\nHR Department",
        read: false,
        attachments: [{ name: "Recruitment_Drive_Details.pdf" }],
    },
    {
        id: "14",
        subject: "Customer Feedback Summary",
        sender: "Customer Support Team",
        date: new Date("2024-03-15T16:00:00"),
        body: "Dear Team, \nHere's a summary of customer feedback from the past month, with suggestions for improvement. \n\nBest regards, \nCustomer Support",
        read: true,
    },
    {
        id: "15",
        subject: "Office Party Planning",
        sender: "Events Team",
        date: new Date("2024-03-18T10:30:00"),
        body: "Hi all, \nWe're planning an office party. Check the attached document for the latest plans and RSVP instructions.\n\nCheers, \nEvents Team",
        read: false,
        attachments: [{ name: "Office_Party_Details.docx" }],
    },
];
